### ISSUE TITLE
Cannot match raise_error with regexp when error message contains UTF-16

### ISSUE THREAD

**Issue by henrahmagix** [rspec/rspec-expectations#1059]
### Subject of the issue
Using `raise_error` with a class and message regex fails when an error is raised that matches the class and message but happens to contain UTF-16 characters.

### Your environment
* Ruby version: 2.4.2
* rspec-expectations version: 3.6.0 (confirmed with 3.7.0 also)

### Steps to reproduce
```ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  gem "rspec", "3.6.0" # Activate the gem and version you are reporting the issue against.
end

puts "Ruby version is: #{RUBY_VERSION}"
require 'rspec/autorun'

RSpec.describe 'raising errors' do
  it 'should match utf-8' do
    expect { raise RuntimeError, 'my foo error' }.to raise_error(RuntimeError, /foo/)
    # pass
  end

  it 'should match utf-8 and utf-16' do
    utf16 = "\n$\x00\x80NY\x91\x16E\x89d\xEC\x03\x1A+\x89&\xDC\xA6D\xC8+\x06\v\xC2\xE7\xBB\x17\x01\b\xA5jK>\xE9\x8B\xE0\x16\x122\x00\xD9\x85\xDB9\x8E#\xE1\x98\xBB\xBA\xBC\x94\xA9\xE0@\xD4\x02\xA5f45\xF2\xBC\xD9[]\xACt\xC2\xC12\f\x83\xFA\x97\xAC\xE9\x04\xE3\x9C\n`\xDE\x18\x7F\xAD\xAEG\x99"
    expect { raise RuntimeError, 'my foo error ' + utf16 }.to raise_error(RuntimeError, /foo/)
    # fail
  end
end
```

### Expected behavior
Both tests should pass.

### Actual behavior
Second test fails:
```
$ ruby test.rb
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Using bundler 1.16.0
Using diff-lcs 1.3
Fetching rspec-support 3.6.0 (was 3.7.1)
Installing rspec-support 3.6.0 (was 3.7.1)
Fetching rspec-core 3.6.0 (was 3.7.1)
Installing rspec-core 3.6.0 (was 3.7.1)
Fetching rspec-expectations 3.6.0 (was 3.7.0)
Installing rspec-expectations 3.6.0 (was 3.7.0)
Fetching rspec-mocks 3.6.0 (was 3.7.0)
Installing rspec-mocks 3.6.0 (was 3.7.0)
Fetching rspec 3.6.0 (was 3.7.0)
Installing rspec 3.6.0 (was 3.7.0)
Ruby version is: 2.4.2
.F

Failures:

  1) raising errors should match utf-8 and utf-16
     Failure/Error: expect { raise RuntimeError, 'my foo error ' + utf16 }.to raise_error(RuntimeError, /foo/)

       expected RuntimeError with message matching /foo/, got #<RuntimeError: my foo error
       $?NY?E?d?+?&ܦD?+
                       ??jK>??2م?9?#ᘻ?????@??f45??[]?t??2
                                                         ??????
       `???G?> with backtrace:
         # test.rb:27:in `block (3 levels) in <main>'
         # test.rb:27:in `block (2 levels) in <main>'
     # test.rb:27:in `block (2 levels) in <main>'

Finished in 0.02171 seconds (files took 0.07927 seconds to load)
2 examples, 1 failure

Failed examples:

rspec test.rb:25 # raising errors should match utf-8 and utf-16
```

**Comment by JonRowe** [comment]
So, `/foo/` here, will be encoded as US-ASCII so its going to be really hard to make this work... (Given: `/foo/ =~ "foo".encode("utf-16")` won't even work) however have you tried composing matchers here? (e.g. using `a_string_matching("foo".encode("utf-16"))`)

**Comment by henrahmagix** [comment]
@JonRowe That gets us somewhere new! Unfortunately I'm now getting a different error :(

```ruby
it 'should match utf-8 and utf-16' do
  utf16 = "\n$\x00\x80NY\x91\x16E\x89d\xEC\x03\x1A+\x89&\xDC\xA6D\xC8+\x06\v\xC2\xE7\xBB\x17\x01\b\xA5jK>\xE9\x8B\xE0\x16\x122\x00\xD9\x85\xDB9\x8E#\xE1\x98\xBB\xBA\xBC\x94\xA9\xE0@\xD4\x02\xA5f45\xF2\xBC\xD9[]\xACt\xC2\xC12\f\x83\xFA\x97\xAC\xE9\x04\xE3\x9C\n`\xDE\x18\x7F\xAD\xAEG\x99"
  expect { raise RuntimeError, "my foo error " + utf16 }.to raise_error(RuntimeError, a_string_matching('foo'.encode('utf-16')))
  # fail
end
```

```
$ ruby test.rb
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Using bundler 1.16.0
Using diff-lcs 1.3
Using rspec-support 3.6.0 (was 3.7.1)
Using rspec-core 3.6.0 (was 3.7.1)
Using rspec-expectations 3.6.0 (was 3.7.0)
Using rspec-mocks 3.6.0 (was 3.7.0)
Using rspec 3.6.0 (was 3.7.0)
Ruby version is: 2.4.2
.F

Failures:

  1) raising errors should match utf-8 and utf-16
     Failure/Error: expect { raise RuntimeError, "my foo error " + utf16 }.to raise_error(RuntimeError, a_string_matching('foo'.encode('utf-16')))

     RegexpError:
       ???????????????????????????
     # test.rb:27:in `block (2 levels) in <main>'
     # ------------------
     # --- Caused by: ---
     # RuntimeError:
     #   my foo error
     #   $?NY?E?d?+?&ܦD?+
                         ??jK>??2م?9?#ᘻ?????@??f45??[]?t??2
                                                           ??????
     #   `???G?
     #   test.rb:27:in `block (3 levels) in <main>'

Finished in 0.01135 seconds (files took 0.15185 seconds to load)
2 examples, 1 failure

Failed examples:

rspec test.rb:25 # raising errors should match utf-8 and utf-16
```

**Comment by pirj** [comment]
Let's factor RuntimeException out:
```ruby
RSpec.describe 'A' do
  it do
    utf16 = "\n$\x00\x80NY\x91\x16E\x89d\xEC\x03\x1A+\x89&\xDC\xA6D\xC8+\x06\v\xC2\xE7\xBB\x17\x01\b\xA5jK>\xE9\x8B\xE0\x16\x122\x00\xD9\x85\xDB9\x8E#\xE1\x98\xBB\xBA\xBC\x94\xA9\xE0@\xD4\x02\xA5f45\xF2\xBC\xD9[]\xACt\xC2\xC12\f\x83\xFA\x97\xAC\xE9\x04\xE3\x9C\n`\xDE\x18\x7F\xAD\xAEG\x99"

    expect('my foo error' + utf16).to match(/foo/)
  end
end
```
gets us:
```
     ArgumentError:
       invalid byte sequence in UTF-8
```

With `force_encoding`:
```ruby
RSpec.describe 'A' do
  it do
    utf16 = "\n$\x00\x80NY\x91\x16E\x89d\xEC\x03\x1A+\x89&\xDC\xA6D\xC8+\x06\v\xC2\xE7\xBB\x17\x01\b\xA5jK>\xE9\x8B\xE0\x16\x122\x00\xD9\x85\xDB9\x8E#\xE1\x98\xBB\xBA\xBC\x94\xA9\xE0@\xD4\x02\xA5f45\xF2\xBC\xD9[]\xACt\xC2\xC12\f\x83\xFA\x97\xAC\xE9\x04\xE3\x9C\n`\xDE\x18\x7F\xAD\xAEG\x99"

    expect('my foo error' + utf16.force_encoding('utf-16')).to match(/foo/)
  end
end
```
it gets us:
```
     Encoding::CompatibilityError:
       incompatible character encodings: UTF-8 and UTF-16
```

It might be a hasty conclusion, but it seems that mixing two different encodings is not really a good idea.

You may match a proper UTF-16 string with an UTF-16 regexp though:
```ruby
  it do
    ni = "你"
    hao = "好"
    hello_in_utf16 = (ni + hao).encode('utf-16')
    nihao = "你好".encode('utf-16')

    expect(hello_in_utf16 ).to match(nihao)
  end
```
This spec passes.

I can't say though if the original string you've provided is a proper UTF-16 or not.

Please feel free to reopen this if you feel that something needs to be improved on RSpec side.

**Comment by henrahmagix** [comment]
Thanks @pirj, sorry I never responded! I'm happy with your conclusion, and your UTF-16-matching example, thanks ☺️
