### ISSUE TITLE
`NoMethodError` in `DelegatorInspector` when #__getobj__ is protected

### ISSUE THREAD

**Issue by jtzero** [rspec/rspec-expectations#1103]
### DelegatorInspector when :__getobj__ is  protected
```
NoMethodError:
       protected method `__getobj__' called for ......
```

### Your environment
* all
* rspec-support 3.8.0

### Steps to reproduce
```
describe 'DelegatorInspector error' do

  describe 'Axiom' do
    class ArgAxiom < SimpleDelegator
    end
    it 'will pass' do
      arg = ArgAxiom.new({hmmm: 'asdf'})
      expect(arg).to have_attributes(any?: true)
    end

    it 'is expected to error' do
      arg = ArgAxiom.new({hmmm: 'asdf'})
      expect(arg).to have_attributes(hmmm: true)
    end
  end

  describe 'Protected' do

    class ArgProtected < SimpleDelegator
      protected :__getobj__
    end
    it 'shouold not error' do
      arg = ArgProtected.new({})
      expect(arg).to have_attributes(any?: true)
    end
    it 'is expected to error' do
      arg = ArgProtected.new({})
      expect(arg).to have_attributes(any?: true)
    end
  end

end
```

### Expected behavior
the following errors shouldn't happen
```
SystemStackError:
       stack level too deep
```
```
NoMethodError:
       protected method `__getobj__' called for {}:ArgProtected
```

all of the errors should look like the Axiom failure
```
Failure/Error: expect(arg).to have_attributes(hmmm: true)
       expected #<ArgAxiom({:hmmm=>"asdf"})> to respond to :hmmm with 0 arguments
```

### Actual behavior
```
.FFFFF

Failures:

  1) DelegatorInspector error Axiom is expected to error
     Failure/Error: expect(arg).to have_attributes(hmmm: true)
       expected #<ArgAxiom({:hmmm=>"asdf"})> to respond to :hmmm with 0 arguments
     # ./tst_spec.rb:13:in `block (3 levels) in <top (required)>'
...
  4) DelegatorInspector error Protected shouold not error
     Failure/Error: expect(arg).to have_attributes(any?: true)
     
     NoMethodError:
       protected method `__getobj__' called for {}:ArgProtected
     # ./tst_spec.rb:40:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   protected method `__getobj__' called for {}:ArgProtected
     #   ./tst_spec.rb:40:in `block (3 levels) in <top (required)>'

  5) DelegatorInspector error Protected is expected to error
     Failure/Error: expect(arg).to have_attributes(any?: true)
     
     NoMethodError:
       protected method `__getobj__' called for {}:ArgProtected
     # ./tst_spec.rb:44:in `block (3 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   protected method `__getobj__' called for {}:ArgProtected
     #   ./tst_spec.rb:44:in `block (3 levels) in <top (required)>'

Finished in 0.01613 seconds (files took 0.08441 seconds to load)
6 examples, 5 failures

Failed examples:

rspec ./tst_spec.rb:11 # DelegatorInspector error Axiom is expected to error
...
rspec ./tst_spec.rb:38 # DelegatorInspector error Protected shouold not error
rspec ./tst_spec.rb:42 # DelegatorInspector error Protected is expected to error
```

edit: removed private references as that is not valid ruby

**Comment by JonRowe** [comment]
:wave: SimpleDelegator does not allow you to use `private` or `protected` for `__getobj__` so this is not an RSpec error, you can produce this in plain Ruby like this:

```
2.5.3 :001 > class A < SimpleDelegator
2.5.3 :002?>   private :__getobj__
2.5.3 :003?>   end
 => A
2.5.3 :004 > A.new({ac: :dc})
SystemStackError: stack level too deep
```

**Comment by jtzero** [comment]
ok for `private` i did not know that however `protected` doesn't seem to be restricted:
```
[1] pry(main)> class Arg < SimpleDelegator
[1] pry(main)*   protected :__getobj__  
[1] pry(main)* end  
=> Arg
[2] pry(main)> a = Arg.new({})
=> {}
[3] pry(main)> a.any?
=> false
```

**Comment by jtzero** [comment]
example of `protected` `__getobj__` https://github.com/cequel/cequel/blob/master/lib/cequel/record/collection.rb#L120-L125

**Comment by JonRowe** [comment]
RSpec never calls this method, it is internal to `SimpleDelegator`.
