### ISSUE TITLE
`failure_message` is never called, but required for `description` to be used

### ISSUE THREAD

**Issue by pirj** [rspec/rspec-expectations#1127]
### Subject of the issue

I'm writing a matcher library, [`rspec-any_of`](https://rubygems.org/gems/rspec-any_of), and have defined matchers in DSL style. However, when refactoring it to use as a matcher class.
Noticed an oddity that if I don't define `failure_message`, `description` is not used.

### Your environment
* Ruby version: 2.5.5
* rspec-expectations version: 3.8.3

### Steps to reproduce

```ruby
# spec/any_of_spec.rb
RSpec.describe 'AnyOf' do
  class AnyOf
    include RSpec::Matchers::Composable

    def initialize(*expected)
      @expected = expected
    end

    def matches?(actual)
      @expected.include?(actual)
    end

    # This never gets called unless you uncomment `failure_message`
    def description(*)
      "any of #{@expected}"
    end

    # def failure_message(*)
    #   fail 'THIS NEVER FAILS!'
    # end
  end

  def any_of(*expected)
    AnyOf.new(*expected)
  end

  def fail_with(*messages)
    raise_error(RSpec::Mocks::MockExpectationError, a_string_including(*messages))
  end

  let(:receiver) { double(:receiver) }

  after(:each, :reset) do
    RSpec::Mocks.space.proxy_for(receiver).reset
  end

  context 'when negated' do
    it 'fails if method is called with a disallowed argument', :reset do
      expect(receiver).not_to receive(:something).with(any_of(1, 2))
      expect { receiver.something(1) }
        .to fail_with('expected: 0 times with arguments: (any of [1, 2])', 'received: 1')
    end
  end
end
```

If you uncomment `failure_message`, the spec pass.
And, apparently, `failure_message` is never used.

### Expected behavior

```
$ rspec spec/any_of_spec.rb
.

Finished in 0.01181 seconds (files took 0.11816 seconds to load)
1 example, 0 failures
```

### Actual behavior

```
F

Failures:

  1) AnyOf when negated fails if method is called with a disallowed argument
     Failure/Error:
       expect { receiver.something(1) }
         .to fail_with('expected: 0 times with arguments: (any of [1, 2])', 'received: 1')

       expected RSpec::Mocks::MockExpectationError with a string including "expected: 0 times with arguments: (any of [1, 2])" and "received: 1", got #<RSpec::Mocks::MockExpectationError: (Double :receiver).something(1)
           expected: 0 times with arguments: (#<AnyOf:0x00007fe4ce3cb0a8 @expected=[1, 2]>)
           received: 1 time with arguments: (1)> with backtrace:
         # ./spec/any_of_spec.rb:40:in `block (4 levels) in <top (required)>'
         # ./spec/any_of_spec.rb:40:in `block (3 levels) in <top (required)>'
     # ./spec/any_of_spec.rb:40:in `block (3 levels) in <top (required)>'

Finished in 0.13998 seconds (files took 0.53775 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/any_of_spec.rb:38 # AnyOf when negated fails if method is called with a disallowed argument
```

**Comment by JonRowe** [comment]
An oddity for sure, we use that method to detect wether an object is a matcher (its part of the protocol) which might be the root cause of the issue.

**Comment by pirj** [comment]
I see. It seems it only affects composable argument matchers, so not a big deal.
Thanks for the clarification!

**Comment by JonRowe** [comment]
Yes so I've looked into this further, and its literally because we expect matchers to conform to our minimum protocol (`matches?` and `failure_message`) (or legacy equivalents) to determine if things are matchers, and further to respond to `describable` if they are to have a description.

However `failure_message` of argument matchers is not used by the rspec-mocks expectation matcher so yes it's never called. If you did `expect(n).to any_of(1,2)` it would be called.

**Comment by pirj** [comment]
Thanks for the insight 👍
