### ISSUE TITLE
Matchers | Custom Failure Message only works for the first failure

### ISSUE THREAD

**Issue by lflucasferreira** [rspec/rspec-expectations#1171]
### Subject of the issue

I realized that the failure message happens only for the first found failure. I was just trying to reproduce what is in [Custom Matchers](https://relishapp.com/rspec/rspec-expectations/v/3-9/docs/custom-matchers/define-a-custom-matcher#overriding-the-failure-message) tutorial.

### Your environment
* Ruby version: **ruby 2.5.7p206 (2019-10-01 revision 67816) [x64-mingw32]**
* rspec-expectations version: **3.9.0**

### Steps to reproduce

The following is the same specification used in the referenced link above:

```ruby
require 'rspec/expectations'

RSpec::Matchers.define :be_a_multiple_of do |expected|
  match do |actual|
    actual % expected == 0
  end
  failure_message do |actual|
    "expected that #{actual} would be a multiple of #{expected}"
  end
end

RSpec.describe 9 do
  it { is_expected.to be_a_multiple_of(3) }
end

RSpec.describe 9 do
  it { is_expected.not_to be_a_multiple_of(4) }
end

# fail intentionally to generate expected output
RSpec.describe 9 do
  it { is_expected.to be_a_multiple_of(4) }
end

# fail intentionally to generate expected output
RSpec.describe 9 do
  it { is_expected.not_to be_a_multiple_of(3) }
end
```

### Expected behavior

The failure message for the second failure would be:

*expected that 9 would be a multiple of 3*
**instead of** 
*expected 9 not to be a multiple of 3*

```bash
  2) 9 is expected not to be a multiple of 3
     Failure/Error: it { is_expected.not_to be_a_multiple_of(3) }
       expected that 9 would be a multiple of 3
     # ./spec/apps/lab_matchers_spec.rb:27:in `block (2 levels) in <top (required)>'
```

### Actual behavior

This is the output for the execution:

```bash
$ rspec
..FF

Failures:

  1) 9 is expected to be a multiple of 4
     Failure/Error: it { is_expected.to be_a_multiple_of(4) }
       expected that 9 would be a multiple of 4
     # ./spec/apps/lab_matchers_spec.rb:22:in `block (2 levels) in <top (required)>'

  2) 9 is expected not to be a multiple of 3
     Failure/Error: it { is_expected.not_to be_a_multiple_of(3) }
       expected 9 not to be a multiple of 3 # <<< HERE IS THE BUG
     # ./spec/apps/lab_matchers_spec.rb:27:in `block (2 levels) in <top (required)>'

Finished in 0.21065 seconds (files took 1.09 seconds to load)
4 examples, 2 failures

Failed examples:

rspec ./spec/apps/lab_matchers_spec.rb:22 # 9 is expected to be a multiple of 4
rspec ./spec/apps/lab_matchers_spec.rb:27 # 9 is expected not to be a multiple of 3
```

**Comment by lflucasferreira** [comment]
Please, ignore this ticket. My fault. 

The second matcher is a negated one.
