### ISSUE TITLE
`include` breaks with a time range

### ISSUE THREAD

**Issue by pirj** [rspec/rspec-expectations#1191]
### Subject of the issue

`include` breaks with a time range

Originally reported by @schwern in https://github.com/rubocop-hq/rubocop-rspec/issues/926

### Your environment

* Ruby version: 2.7.1
* rspec-expectations version: `master` ([`eb1787f`](https://github.com/rspec/rspec-expectations/commit/eb1787f0e1a5ec2c2650048ee60a45d4c9738d78))

### Steps to reproduce

```ruby
RSpec.describe 'include' do
  it do # works
    range = (3..5)
    expect(range).not_to include(6)
  end

  range = (Time.now-20...Time.now-10)
  now = Time.now

  it do # works
    expect(range.include?(now)).not_to be true
  end

  it do # breaks
    expect(range).not_to include(now)
  end
end
```

### Expected behavior

All examples pass

### Actual behavior

The example with a time range and `include` matcher fails with:
```
  1) include is expected not to include 2020-06-11 10:47:01.120378000 +0300
     Failure/Error: expect(range).not_to include(now)

     TypeError:
       can't iterate from Time
     # ./lib/rspec/matchers/built_in/include.rb:134:in `each'
     # ./lib/rspec/matchers/built_in/include.rb:134:in `any?'
     # ./lib/rspec/matchers/built_in/include.rb:134:in `actual_collection_includes?'
```

**Comment by schwern** [comment]
It breaks on Float as well.

```
require 'rspec'

describe 'include' do
  it 'is not equivalent' do
    obj = 2.5
    range = (obj...obj)
    expect(range.include?(obj)).to be_falsey  # pass
    expect(range).not_to include(obj)  # TypeError: can't iterate from Float
  end
end
```

**Comment by bclayman-sq** [comment]
Hi @pirj, @schwern, @JonRowe!  I just put out a PR that attempts to address this issue.  Would one of you mind giving it a review when you get a chance?

**Comment by pirj** [comment]
@bclayman-sq Certainly. We're always watching. 👀

**Comment by bclayman-sq** [comment]
Hi @pirj, thanks again for kicking off those builds for me!  My PR passes CI for ruby >= 2.1.9 but my `Time` tests fail for legacy ruby builds (<= 2.0).  I installed 2.0 locally and re-ran my tests to see why those tests fail with `Can't iterate from Time` exceptions.  However, they all pass for me.

I looked at the changelog for ruby 2.1 but nothing about `Range` or `Time` jumped out at me as something that might cause tests with a newer ruby version to succeed and those using an older version to fail.

Could you tell me more about those legacy builds in CI and why these tests might fail on older ruby versions but not newer ones?  I'd love some guidance on what might be happening here if you have a minute!

**Comment by bclayman-sq** [comment]
Hi @pirj, thanks again for kicking off those builds for me! My PR passes CI for ruby >= 2.1.9 but my Time tests fail for legacy ruby builds (<= 2.0). Installing 2.0 locally is a bit of a minefield, unfortunately 😦 .

I looked at the changelog for ruby 2.1 but nothing about Range or Time jumped out at me as something that might cause tests with a newer ruby version to succeed and those using an older version to fail.

I have two asks:

1. Could you tell me more about those legacy builds in CI and why these tests might fail on older ruby versions but not newer ones? I'd love some guidance on what might be happening here if you have a minute!

2. Alternatively, is it possible to enable a more detailed stack trace for a legacy build?  

Currently, the failing tests with a legacy ruby version only reference the test lines, not the source of the raised `TypeError`:

```
expected RSpec::Expectations::ExpectationNotMetError with message matching /expected\ 2021\-10\-04\ 22:16:12\ UTC\.\.2021\-10\-04\ 22:16:22\ UTC\ not\ to\ include\ 2021\-10\-04\ 22:16:12\.525844271\ \+0000\ once\ but\ it\ is\ included\ once/, got #<TypeError: can't iterate from Time> with backtrace:
 # ./spec/rspec/matchers/built_in/include_spec.rb:836:in `block (8 levels) in <top (required)>'
 # ./spec/rspec/matchers/built_in/include_spec.rb:835:in `block (7 levels) in <top (required)>'
# ./spec/rspec/matchers/built_in/include_spec.rb:835:in `block (7 levels) in <top (required)>'
```

**Comment by bclayman-sq** [comment]
Hi @pirj, thanks again for kicking off those builds for me!

I've fixed up a couple issues causing a failing build and think this one should pass.  In particular, I've now targeted ruby versions >= 2.1.9 for this improvement.  Assuming CI passes, I'll update the docs to indicate these improvements are available for >= 2.1.9.  How does that sound to you?

**Comment by schwern** [comment]
Bump.
