### ISSUE TITLE
Weird output behavior when using compound expectations

### ISSUE THREAD

**Issue by noon-ng** [rspec/rspec-expectations#1323]
### Subject of the issue
Certain combinations of compound expectations print a failure description twice, but not if `have_attributes` is used.

### Your environment
* Ruby version: 2.7.2
* rspec-expectations version: 3.10.1

### Steps to reproduce

Let's say you have a test file with these contents and run it with `--format=documentation`

```ruby
# spec/hello_spec.rb

Hello = Struct.new(:a, :b) do
  def valid?
    a == b
  end
end

RSpec.describe Hello do
  subject(:hello) { invalid_hello }
  let(:invalid_hello) { Hello.new(1, 2) }
  it { is_expected.to be_a(Hash).and(be_valid) }
  it { is_expected.to be_valid.and(be_valid) }
  it { is_expected.to be_valid.and(have_attributes(a: 1, b: 1)) }
  it { is_expected.to be_valid.and(be_a(Hash)).and(be_a(Hash)) }
  it { is_expected.to be_valid.and(be_a(Hash)).and(have_attributes(a: 1, b: 1)) }
end
```

### Expected behavior
All examples should fail and output their failure messages the same number of times.

### Actual behavior
Examples with `have_attributes` print their output once; examples without print their output twice (first in red, then in the default shell color).

```
Failures:

  1) Hello is expected to be a kind of Hash and be valid truthy
     Failure/Error: it { is_expected.to be_a(Hash).and(be_valid) }

          expected #<Hello:0x00007fcf09083290> to be a kind of Hash

       ...and:

          expected #<struct Hello a=1, b=2> to be valid
          expected #<Hello:0x00007fcf09083290> to be a kind of Hash

       ...and:

          expected #<struct Hello a=1, b=2> to be valid
     # ./spec/hello_spec.rb:14:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:59:in `block (2 levels) in <main>'
     # -e:1:in `<main>'

  2) Hello is expected to be valid truthy and be valid truthy
     Failure/Error: it { is_expected.to be_valid.and(be_valid) }

          expected #<struct Hello a=1, b=2> to be valid

       ...and:

          expected #<struct Hello a=1, b=2> to be valid
          expected #<struct Hello a=1, b=2> to be valid

       ...and:

          expected #<struct Hello a=1, b=2> to be valid
     # ./spec/hello_spec.rb:15:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:59:in `block (2 levels) in <main>'
     # -e:1:in `<main>'

  3) Hello is expected to be valid truthy and have attributes (a: 1, b: 1)
     Failure/Error: it { is_expected.to be_valid.and(have_attributes(a: 1, b: 1)) }

          expected #<struct Hello a=1, b=2> to be valid

       ...and:

          Expected #<Hello:0x00007fcf09c6ce08> to have attributes (a: 1, b: 1).
     # ./spec/hello_spec.rb:16:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:59:in `block (2 levels) in <main>'
     # -e:1:in `<main>'

  4) Hello is expected to be valid truthy and be a kind of Hash and be a kind of Hash
     Failure/Error: it { is_expected.to be_valid.and(be_a(Hash)).and(be_a(Hash)) }

             expected #<struct Hello a=1, b=2> to be valid

          ...and:

             expected #<Hello:0x00007fcf09eb6290> to be a kind of Hash

       ...and:

          expected #<Hello:0x00007fcf09eb6290> to be a kind of Hash
             expected #<struct Hello a=1, b=2> to be valid

          ...and:

             expected #<Hello:0x00007fcf09eb6290> to be a kind of Hash

       ...and:

          expected #<Hello:0x00007fcf09eb6290> to be a kind of Hash
     # ./spec/hello_spec.rb:17:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:59:in `block (2 levels) in <main>'
     # -e:1:in `<main>'

  5) Hello is expected to be valid truthy and be a kind of Hash and have attributes (a: 1, b: 1)
     Failure/Error: it { is_expected.to be_valid.and(be_a(Hash)).and(have_attributes(a: 1, b: 1)) }

             expected #<struct Hello a=1, b=2> to be valid

          ...and:

             expected #<Hello:0x00007fcf09f1c6f8> to be a kind of Hash

       ...and:

          Expected #<Hello:0x00007fcf09f1c6f8> to have attributes (a: 1, b: 1).
     # ./spec/hello_spec.rb:18:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:59:in `block (2 levels) in <main>'
     # -e:1:in `<main>'
```

**Comment by noon-ng** [comment]
I was rejigging this quite a bit to understand how the output would change and copy/pasted the wrong version - the first example was actually meant to be `is_expected.to be_a(Hash).and(be_valid)`, creating the following output:

```
Failures:

  1) Hello is expected to be a kind of Hash and be valid truthy
     Failure/Error: it { is_expected.to be_a(Hash).and(be_valid) }

          expected #<Hello:0x00007fcf09083290> to be a kind of Hash

       ...and:

          expected #<struct Hello a=1, b=2> to be valid
          expected #<Hello:0x00007fcf09083290> to be a kind of Hash

       ...and:

          expected #<struct Hello a=1, b=2> to be valid
     # ./spec/hello_spec.rb:14:in `block (2 levels) in <top (required)>'
     # ./spec/rails_helper.rb:59:in `block (2 levels) in <main>'
     # -e:1:in `<main>'
```

Apologies for the added contrivance 😅

**Comment by pirj** [comment]
Please don't hesitate to edit the description so we can start the discussion from the clean slate.
In a nutshell, is my understanding correct that you find the difference in output of the following two examples confusing and incorrect?
```ruby
  it { is_expected.to be_present.and(be_valid) }
  it { is_expected.to be_present.and(have_attributes(a: 1, b: 1)) }
```

I can't reproduce duplication (using `4-0-dev` branch, but there should be no difference):
```
  1) Hello is expected to be valid and have attributes {:a => 1, :b => 1}
     Failure/Error: it { is_expected.to be_valid.and(have_attributes(a: 1, b: 1)) }

          expected `#<struct Hello a=1, b=2>.valid?` to return true, got false

       ...and:

          expected #<struct Hello a=1, b=2> to have attributes {:a => 1, :b => 1} but had attributes {:a => 1, :b => 2}
       Diff for (have attributes {:a => 1, :b => 1}):
       @@ -1,3 +1,2 @@
       -:a => 1,
       -:b => 1,
       +"#<struct Hello a=1, b=2>"

  2) Hello is expected to be valid and be valid
     Failure/Error: it { is_expected.to be_valid.and(be_valid) }

          expected `#<struct Hello a=1, b=2>.valid?` to return true, got false

       ...and:

          expected `#<struct Hello a=1, b=2>.valid?` to return true, got false

  3) Hello is expected to be a kind of Hash and have attributes {:a => 1, :b => 1}
     Failure/Error: it { is_expected.to be_a(Hash).and(have_attributes(a: 1, b: 1)) }

          expected #<struct Hello a=1, b=2> to be a kind of Hash

       ...and:

          expected #<struct Hello a=1, b=2> to have attributes {:a => 1, :b => 1} but had attributes {:a => 1, :b => 2}
       Diff for (have attributes {:a => 1, :b => 1}):
       @@ -1,3 +1,2 @@
       -:a => 1,
       -:b => 1,
       +"#<struct Hello a=1, b=2>"

  4) Hello is expected to be valid and be a kind of Hash and have attributes {:a => 1, :b => 1}
     Failure/Error: it { is_expected.to be_valid.and(be_a(Hash)).and(have_attributes(a: 1, b: 1)) }

             expected `#<struct Hello a=1, b=2>.valid?` to return true, got false

          ...and:

             expected #<struct Hello a=1, b=2> to be a kind of Hash

       ...and:

          expected #<struct Hello a=1, b=2> to have attributes {:a => 1, :b => 1} but had attributes {:a => 1, :b => 2}
       Diff for (have attributes {:a => 1, :b => 1}):
       @@ -1,3 +1,2 @@
       -:a => 1,
       -:b => 1,
       +"#<struct Hello a=1, b=2>"

  5) Hello is expected to be valid and be a kind of Hash and be a kind of Hash
     Failure/Error: it { is_expected.to be_valid.and(be_a(Hash)).and(be_a(Hash)) }

             expected `#<struct Hello a=1, b=2>.valid?` to return true, got false

          ...and:

             expected #<struct Hello a=1, b=2> to be a kind of Hash

       ...and:

          expected #<struct Hello a=1, b=2> to be a kind of Hash
```

Can you reproduce this on a freshly initialized project?

**Comment by noon-ng** [comment]
I'll update the issue, and give the example a go in 4.0-dev.

Re: your question, I think you got it  - in that `have_attributes` seems to change the output - but that snippet wouldn't manifest the issue, since in each example only one term of the compound fails.

What I'm finding confusing is that it seems that when _more than one term_ of the compound expectation fails, then the output is doubled, _except if the test uses `have_attributes`_:

```ruby
it { is_expected.to satisfy { |_| false }.and(be_valid) }
it { is_expected.to satisfy { |_| false }.and(have_attributes(a: 1, b: 1)) }
```

yields

```
  1) Hello is expected to satisfy expression `false` and be valid truthy
     Failure/Error: it { is_expected.to satisfy { |_| false }.and(be_valid) }

          expected #<Hello:0x00007fcf099bd400> to satisfy expression `false`

       ...and:

          expected #<struct Hello a=1, b=2> to be valid
          expected #<Hello:0x00007fcf099bd400> to satisfy expression `false`

       ...and:

          expected #<struct Hello a=1, b=2> to be valid

  2) Hello is expected to satisfy expression `false` and have attributes (a: 1, b: 1)
     Failure/Error: it { is_expected.to satisfy { |_| false }.and(have_attributes(a: 1, b: 1)) }

          expected #<Hello:0x00007fcf09bdcce0> to satisfy expression `false`

       ...and:

          Expected #<Hello:0x00007fcf09bdcce0> to have attributes (a: 1, b: 1).
```

**Comment by noon-ng** [comment]
Yup, can't reproduce in 4-0-dev.

**Comment by noon-ng** [comment]
Couldn't reproduce in a clean 3.10.1 environment either, so this is probably an issue with my RSpec environment. Feel free to close.

**Comment by noon-ng** [comment]
(Thanks for taking a look!)
