### ISSUE TITLE
[Ruby 3] - ArgumentError when integrating with capybara 

### ISSUE THREAD

**Issue by alecslupu** [rspec/rspec-expectations#1329]
### Subject of the issue
While upgrading to Ruby 3, writing a test like: 
```expect(subject).to have_css(".comment__reply", count: 2)```

Will raise an ArgumentError `wrong number of arguments (given 2, expected 1)`

### Your environment
* Ruby version: 3.0.2
* rspec-expectations version: 3.10.1
* capybara version: 3.35.2

### Expected behavior
Running the same test in Ruby 2.7 
```expect(subject).to have_css(".comment__reply", count: 2)``` 
works without any issues, but it fails when running in using Ruby 3.0.2

### Actual behavior
An error is thrown: 

```
 7) Decidim::Comments::CommentCell when rendering when signed in renders the reply form
     Failure/Error: expect(subject).to have_css(".comment__reply", count: 2)
     
     ArgumentError:
       wrong number of arguments (given 2, expected 1)
     # /bundle_cache/ruby/3.0.0/gems/capybara-3.35.2/lib/capybara/node/matchers.rb:309:in `has_css?'
     # /bundle_cache/ruby/3.0.0/gems/rspec-expectations-3.10.1/lib/rspec/matchers/built_in/has.rb:67:in `predicate_result'
     # /bundle_cache/ruby/3.0.0/gems/rspec-expectations-3.10.1/lib/rspec/matchers/built_in/has.rb:78:in `predicate_matches?'
     # /bundle_cache/ruby/3.0.0/gems/rspec-expectations-3.10.1/lib/rspec/matchers/built_in/has.rb:19:in `matches?'
     # /bundle_cache/ruby/3.0.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/handler.rb:51:in `block in handle_matcher'
     # /bundle_cache/ruby/3.0.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /bundle_cache/ruby/3.0.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /bundle_cache/ruby/3.0.0/gems/rspec-expectations-3.10.1/lib/rspec/expectations/expectation_target.rb:65:in `to'
     # ./spec/cells/decidim/comments/comment_cell_spec.rb:153:in `block (4 levels) in <module:Comments>'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `instance_exec'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:262:in `block in run'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `block in with_around_and_singleton_context_hooks'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `block in with_around_example_hooks'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `block in run'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
     # /bundle_cache/ruby/3.0.0/gems/rspec-cells-0.3.5/lib/rspec/cells/example_group.rb:43:in `block (2 levels) in <module:ExampleGroup>'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
     # /bundle_cache/ruby/3.0.0/gems/rspec-rails-4.1.2/lib/rspec/rails/adapters.rb:75:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
     # /bundle_cache/ruby/3.0.0/gems/webmock-3.13.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <main>'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:455:in `instance_exec'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:390:in `execute_with'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:350:in `call'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/hooks.rb:486:in `run'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:465:in `with_around_example_hooks'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:508:in `with_around_and_singleton_context_hooks'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example.rb:259:in `run'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:644:in `block in run_examples'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `map'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:640:in `run_examples'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:606:in `run'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `block in run'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `map'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `run'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `block in run'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `map'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/example_group.rb:607:in `run'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `map'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/configuration.rb:2067:in `with_suite_hooks'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/reporter.rb:74:in `report'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:115:in `run_specs'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:89:in `run'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:71:in `run'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/lib/rspec/core/runner.rb:45:in `invoke'
     # /bundle_cache/ruby/3.0.0/gems/rspec-core-3.10.1/exe/rspec:4:in `<top (required)>'
     # ../bin/rspec:26:in `load'
     # ../bin/rspec:26:in `<main>'
```

**Comment by jason-o-matic** [comment]
I think this is still a problem. It looks like https://github.com/rspec/rspec-expectations/blob/b79a5c9/lib/rspec/matchers/built_in/has.rb#L67 calls https://github.com/teamcapybara/capybara/blob/2fd00e5/lib/capybara/node/matchers.rb#L310 but rspec is sending positional args and capybara is expecting keyword args. Off the top of my head it seems like rspec should pass through both positional and keyword arguments.

**Comment by JonRowe** [comment]
Capybara may need to mark their method as taking `ruby2_keywords`
