### ISSUE TITLE
error_highlight fix #1339 does not correctly report the issue

### ISSUE THREAD

**Issue by voxik** [rspec/rspec-expectations#1362]
Trying to execute Thor test suite with rspec-expectations 3.11.0 + Ruby 3.1, I observe the following error:

~~~
  1) Thor::Options#parse raises an error for unknown switches
     Failure/Error: expect { check_unknown! }.to raise_error(Thor::UnknownArgumentError, expected)

       expected Thor::UnknownArgumentError with "Unknown switches \"--baz\"\nDid you mean?  \"--bar\"", got #<Thor::UnknownArgumentError: Unknown switches "--baz"
       Did you mean?  "--bar"> with backtrace:
         # ./lib/thor/parser/options.rb:146:in `check_unknown!'
         # ./spec/parser/options_spec.rb:17:in `check_unknown!'
         # ./spec/parser/options_spec.rb:119:in `block (4 levels) in <top (required)>'
         # ./spec/parser/options_spec.rb:119:in `block (3 levels) in <top (required)>'
         # /usr/share/gems/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
     # ./spec/parser/options_spec.rb:119:in `block (3 levels) in <top (required)>'
     # /usr/share/gems/gems/webmock-3.14.0/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
~~~

This brought me to the #1339, which is the reason for the error message, but I don't think the reported error is correct. It should actually be:

~~~
       expected Thor::UnknownArgumentError with "Unknown switches \"--baz\"\nDid you mean?  \"--bar\"", got #<Thor::UnknownArgumentError: Unknown switches "--baz"> with backtrace:
~~~

IOW it should not mention the `Did you mean?  "--bar"`, because the `original_message` was used for the comparison. I think that [this line](https://github.com/rspec/rspec-expectations/blob/9efe040e8e9002f88452e27e2e217fa776c96a17/lib/rspec/matchers/built_in/raise_error.rb#L248) should be adjusted.

This is the test case in question:

https://github.com/rails/thor/blob/ab3b5be455791f4efb79f0efb4f88cc6b59c8ccf/spec/parser/options_spec.rb#L112-L120

**Comment by voxik** [comment]
This IMO belongs into same bucket as https://github.com/rspec/rspec-mocks/issues/1460 and the error message should give even more details what is going on, because this is not transparent, especially at the time a lot of places are already adjusted to account for DidYouMean

**Comment by pirj** [comment]
It seems that `expected` is missing indentation:
```
# actual
Unknown switches "--baz"
       Did you mean?  "--bar"
```
vs
```
# expected
Unknown switches "--baz"
Did you mean?  "--bar"
```

**Comment by JonRowe** [comment]
I'm open to improving the error output of this matcher, I don't think its automatically diffed, so it could improve its output when the class matches but the message differs, even leveraging the differ for the error string. Want to have a go at this @voxik?

**Comment by voxik** [comment]
> WDYT of changing this to something like?
> 
> ```ruby
> values_match?(@expected_message, actual_error_message.to_s) || values_match?(@expected_message, @actual_error.message)
> ```

I think that this would be good if you preferred backward compatibility and keep the test suite working.

However, as I said, this IMO belongs to the same bucket as https://github.com/rspec/rspec-mocks/issues/1460 (it covers new Ruby functionality, but it is not very clear what is going on) and therefore the functionality should stay as it is, the error message should provide more information and all the test suites will need to be adjusted.

On top of that RSpec could be extended to be able to test the original output (which is the current situation, but was not the case previously) as well as the output mangled by did_you_mean/error_highlight (if this is deemed interesting, testing the original is probably more valuable).

IOW I'd say that the proposed solution could be enough to fix the behavior but the "right breaking" behavior should be introduced at some right milestone.
