### ISSUE TITLE
The `define_negated_matcher` is broken for matchers with named parameters in Ruby 3

### ISSUE THREAD

**Issue by bfad** [rspec/rspec-expectations#1393]
If you have a matcher that allows for named parameters, and then you use `RSpec::Matchers.define_negated_matcher` to create a negated version, the negated version has argument errors when used in Ruby 3. (I have confirmed that this works in Ruby 2.7.6.)

## Your environment
* Ruby version: 3.0.3
* rspec-expectations version: 3.12.0

## Steps to reproduce

``` ruby
#!/usr/bin/env ruby
# frozen_string_literal: true

begin
  require "bundler/inline"
rescue LoadError => e
  $stderr.puts "Bundler version 1.10 or later is required. Please update your Bundler"
  raise e
end

gemfile(true) do
  source "https://rubygems.org"

  gem "rspec", "3.12.0" # Activate the gem and version you are reporting the issue against.
end

puts "Ruby version is: #{RUBY_VERSION}"
require 'rspec/autorun'


module ComplexMatchers
  class Match
    include RSpec::Matchers::Composable

    attr_accessor :my_reqs, :my_opts, :my_block

    def initialize(required, **options, &block)
      self.my_reqs = required
      self.my_opts = options
      self.my_block = block
    end

    def matches?(val)
      true
    end
  end

  def complex_match(...)
    Match.new(...)
  end
end


RSpec.describe 'additions' do
  include ComplexMatchers
  RSpec::Matchers.define_negated_matcher :complex_missing, :complex_match

  it 'just succeeds' do
    expect(2).to complex_match("foo", bar: 33, baz: 22)
  end

  it 'succeeds because negated' do
    expect(2).not_to complex_missing("foo", bar: 33, baz: 22)
  end
end
```

## Expected behavior

Both tests pass

## Actual behavior

Console output:
```
Ruby version is: 3.0.3

additions
  just succeeds
  succeeds because negated (FAILED - 1)

Failures:

  1) additions succeeds because negated
     Failure/Error:
       def initialize(required, **options, &block)
         self.my_reqs = required
         self.my_opts = options
         self.my_block = block
       end
     
     ArgumentError:
       wrong number of arguments (given 2, expected 1)
     # bin/repo_rspec.rb:30:in `initialize'
     # bin/repo_rspec.rb:42:in `new'
     # bin/repo_rspec.rb:42:in `complex_match'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-expectations-3.12.0/lib/rspec/matchers/dsl.rb:39:in `block in alias_matcher'
     # bin/repo_rspec.rb:56:in `block (2 levels) in <main>'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:263:in `instance_exec'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:263:in `block in run'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:486:in `block in run'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:624:in `run_around_example_hooks_for'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/hooks.rb:486:in `run'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/example.rb:259:in `run'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:642:in `map'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:642:in `run_examples'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/example_group.rb:607:in `run'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `map'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/configuration.rb:2070:in `with_suite_hooks'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/reporter.rb:74:in `report'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:115:in `run_specs'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:89:in `run'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:71:in `run'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:45:in `invoke'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:38:in `perform_at_exit'
     # /path/to/repro/vendor/ruby/3.0.0/gems/rspec-core-3.12.0/lib/rspec/core/runner.rb:24:in `block in autorun'
     # 
     #   Showing full backtrace because every line was filtered out.
     #   See docs for RSpec::Configuration#backtrace_exclusion_patterns and
     #   RSpec::Configuration#backtrace_inclusion_patterns for more information.

Finished in 0.00142 seconds (files took 0.05359 seconds to load)
2 examples, 1 failure

Failed examples:

rspec bin/repo_rspec.rb:55 # additions succeeds because negated
```

**Comment by bfad** [comment]
> A one-line change turns it green:
> 
> ```diff
> -    def initialize(required, **options, &block)
> +    def initialize(required, *options, &block)
> ```
> 
> See [this blog post](https://eregon.me/blog/2021/02/13/correct-delegation-in-ruby-2-27-3.html) for more info on this topic.

The problem is that they are named parameters, not positional parameters, so that change isn't helpful. (Also wouldn't be helpful in the case where you had variable number of positional parameters as well as named parameters.)

> Would you still be able to break RSpec with a less minified example? I suppose you do use those `my_opts`.

I minified my example from a more complex matcher to make the issue clearer. In the actual matcher, we do use the named parameters values.

**Comment by pirj** [comment]
> named parameters

Do you mean keyword arguments, or just an options hash?

There is some lack of understanding going on. May I kindly ask you to provide your matcher code with no simplifications?

**Comment by bfad** [comment]
> > named parameters
> 
> Do you mean keyword arguments, or just an options hash?

I am talking about keyword arguments.

> 
> There is some lack of understanding going on. May I kindly ask you to provide your matcher code with no simplifications?

I don't see how providing my full matcher would provide fuller clarity for this issue. It would explain why I have a matcher that takes variadic keyword arguments, but that doesn't help point out the issue. From my perspective, the issue seems to be that when RSpec defines the negated matcher, [it wraps the original matcher](https://github.com/rspec/rspec-expectations/blob/61fe1bc203fa7b906d3034401fa90f1115cb48ae/lib/rspec/matchers/dsl.rb#L38-L42) in such a way that prevents it from passing the keyword arguments to the original matcher.

**Comment by JonRowe** [comment]
:wave: Sorry you are experiencing this problem, RSpec did not originally officially support keyword arguments to its internals due to our supporting Ruby matrix, as people have grown their usage of them in various places they just worked on Ruby 2.x, the Ruby 3.x changes splitting them out has caused numerous errors due to our "ruby 2 keywords" style usage and this is one. We can't yet solve this by using `**kwargs` but we can try marking our methods as ruby 2 keywords for Ruby 3, in the mean time you can fix this by making your matcher `*args` and marking it as ruby2_keywords.

**Comment by JonRowe** [comment]
I think #1394 solves this, at least based on my quick tests, please check it out to see if it works with your matcher.
