### ISSUE TITLE
Consider deprecating `expect { }.not_to raise_error(SpecificErrorClass)`

### ISSUE THREAD

**Issue by myronmarston** [rspec/rspec-expectations#231]
An expression like `expect { }.not_to raise_error` is fine, as it expresses intent (particularly when paired with a corresponding example that demonstrates when a particular error is raised), but `expect { }.not_to raise_error(SpecificErrorClass)` is dangerous.  It's prone to producing false positives.  Consider:

``` ruby
expect {
  expect(some_helper(foo)).to eq(:bar)
}.not_to raise_error(SomeError)
```

With this in place, it's _impossible_ for the inner expectation to ever cause the example to fail.  When the inner expectation fails, it raises a `RSpec::Expectations::ExpectationNotMetError`, but this is not a `SomeError`, so the outer expectation causes it to pass.

Thus, I think we should deprecate a specific error class with the negative `raise_error` matching.  In 3.0 it'd be nice to disallow it entirely.

**Comment by myronmarston** [comment]
For anyone who still wants a replacement, there's a pretty simple way in RSpec 3.1+ (3.1 is the first release to have `define_negated_matcher`) to get it back, with an expectation that is _much more explicit_ about what it's doing (and thus, IMO, better than what we had before):

``` ruby
RSpec::Matchers.define_negated_matcher :an_error_other_than, :an_instance_of
 
RSpec.describe "Using `an_error_other_than` as an argument to `raise_error`" do
  example "passing" do
    expect {
      raise ArgumentError
    }.to raise_error(an_error_other_than(SyntaxError))
  end
 
  example "failing" do
    expect {
      raise SyntaxError
    }.to raise_error(an_error_other_than(SyntaxError))
  end
end
```

Running this produces:

```
Using `an_error_other_than` as an argument to `raise_error`
  failing (FAILED - 1)
  passing
 
Failures:
 
  1) Using `an_error_other_than` as an argument to `raise_error` failing
     Failure/Error: expect {
       expected an error other than SyntaxError, got #<SyntaxError: SyntaxError> with backtrace:
         # ./spec/raise_error_spec.rb:12:in `block (3 levels) in <top (required)>'
         # ./spec/raise_error_spec.rb:11:in `block (2 levels) in <top (required)>'
     # ./spec/raise_error_spec.rb:11:in `block (2 levels) in <top (required)>'
 
Finished in 0.00248 seconds (files took 0.11564 seconds to load)
2 examples, 1 failure
 
Failed examples:
 
rspec ./spec/raise_error_spec.rb:10 # Using `an_error_other_than` as an argument to `raise_error` failing
```

Note that this isn't exactly the same: `expect { }.not_to raise_error(SyntaxError)` would pass if no error was raised or if any other type of error was raised.  However, these two cases are entirely different, and IMO, if you want the former case, then `expect { }.not_to raise_error` is much better, and for the latter case, this is much more explicit about what it is actually doing.
