### ISSUE TITLE
Undefined method on AnyArgsMatcher

### ISSUE THREAD

**Issue by mhenrixon** [rspec/rspec-expectations#732]
The following spec

```ruby
it "tries to send the middle of the month bills", :focus do
  expect(subject).to receive(:send_due_bills).with(Month.new(11, 2012), "middle")
  subject.send_bills_for_dues_subscription_this_month
end
```

Yields the following error in rspec 3.2

```
1) BillScheduler.send_bills_for_dues_subscription_this_month when it's the middle of the month tries to send the middle of the month bills
     Failure/Error: expect(subject).to receive(:send_due_bills).with(Month.new(11, 2012), "middle")
     NoMethodError:
       undefined method `month' for #<RSpec::Mocks::ArgumentMatchers::AnyArgsMatcher:0x007f91b2c031b8>
     # ./lib/month.rb:40:in `=='
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-mocks-3.2.0/lib/rspec/mocks/argument_list_matcher.rb:84:in `count'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-mocks-3.2.0/lib/rspec/mocks/argument_list_matcher.rb:84:in `ensure_expected_args_valid!'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-mocks-3.2.0/lib/rspec/mocks/argument_list_matcher.rb:47:in `initialize'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-mocks-3.2.0/lib/rspec/mocks/message_expectation.rb:324:in `new'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-mocks-3.2.0/lib/rspec/mocks/message_expectation.rb:324:in `with'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-mocks-3.2.0/lib/rspec/mocks/verifying_message_expecation.rb:26:in `with'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-mocks-3.2.0/lib/rspec/mocks/matchers/expectation_customization.rb:15:in `playback_onto'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-mocks-3.2.0/lib/rspec/mocks/matchers/receive.rb:99:in `block in setup_method_substitute'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-mocks-3.2.0/lib/rspec/mocks/matchers/receive.rb:98:in `each'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-mocks-3.2.0/lib/rspec/mocks/matchers/receive.rb:98:in `setup_method_substitute'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-mocks-3.2.0/lib/rspec/mocks/matchers/receive.rb:84:in `setup_mock_proxy_method_substitute'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-mocks-3.2.0/lib/rspec/mocks/matchers/receive.rb:24:in `setup_expectation'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-expectations-3.2.0/lib/rspec/expectations/handler.rb:50:in `block in handle_matcher'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-expectations-3.2.0/lib/rspec/expectations/handler.rb:27:in `with_matcher'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-expectations-3.2.0/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-expectations-3.2.0/lib/rspec/expectations/expectation_target.rb:54:in `to'
     # ./spec/models/bill_scheduler_spec.rb:47:in `block (4 levels) in <top (required)>'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example.rb:177:in `instance_exec'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example.rb:177:in `block in run'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example.rb:385:in `block in with_around_and_singleton_context_hooks'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example.rb:343:in `block in with_around_example_hooks'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/hooks.rb:474:in `block in run'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/hooks.rb:614:in `block in run_around_example_hooks_for'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example.rb:247:in `call'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example.rb:247:in `call'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-rails-3.2.0/lib/rspec/rails/adapters.rb:111:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example.rb:333:in `instance_exec'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example.rb:333:in `instance_exec'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/hooks.rb:387:in `execute_with'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/hooks.rb:616:in `block (2 levels) in run_around_example_hooks_for'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example.rb:247:in `call'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example.rb:247:in `call'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/hooks.rb:617:in `run_around_example_hooks_for'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/hooks.rb:474:in `run'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example.rb:343:in `with_around_example_hooks'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example.rb:385:in `with_around_and_singleton_context_hooks'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example.rb:174:in `run'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:548:in `block in run_examples'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:544:in `map'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:544:in `run_examples'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:512:in `run'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:513:in `block in run'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:513:in `map'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:513:in `run'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:513:in `block in run'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:513:in `map'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/example_group.rb:513:in `run'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:110:in `block (3 levels) in run_specs'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:110:in `map'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:110:in `block (2 levels) in run_specs'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/configuration.rb:1526:in `with_suite_hooks'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:109:in `block in run_specs'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/reporter.rb:62:in `report'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:108:in `run_specs'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:86:in `run'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:70:in `run'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/lib/rspec/core/runner.rb:38:in `invoke'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/gems/rspec-core-3.2.0/exe/rspec:4:in `<top (required)>'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/bin/rspec:23:in `load'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/bin/rspec:23:in `<main>'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `eval'
     # /Users/mhenrixon/.rvm/gems/ruby-2.1.2/bin/ruby_executable_hooks:15:in `<main>'
```

Now that I look at the stack trace I am afraid this should be in RSpec mocks perhaps.

**Comment by mhenrixon** [comment]
If I downgrade to RSpec 3.1 it works as expected (pun intended)

**Comment by myronmarston** [comment]
Can you paste the definition of `Month#==` from `lib/month.rb` (around line 40)?

I suspect that your definition is written to assume it will only ever be called with another `Month` object, and indiscriminately calls `month` on the passed arg.  The Ruby semantics of `==` are that it returns `true` or `false` to indicate equality or not.  Raising an exception from your `==` is a violation of the semantics RSpec expects for `==`.  The logic put in place for rspec/rspec-mocks#786 has a spot where it does `expected_arg_list.count(any_args_matcher)` which has the effect of calling `== any_args_macher` on each arg in the list and that's getting an exception when it calls `Month#==`.  One simple solution is to add a `return false unless other.is_a?(Month)` as the first line in `Month#==`.

**Comment by orien** [comment]
I'm running into this as well. It'd be nice if all classes had correct implementations of `#==`. But that is impossible to guarantee.

From an RSpec perspective I'd say arguments with incorrect `#==` implementations are included in the set of _any_ args. Thus the any args matcher should match them.

**Comment by JonRowe** [comment]
We've discussed this before, RSpec like other ruby libraries expects you to follow Ruby's interface conventions, one of which is making `#==` return a truthy / falsey value for any object.

**Comment by myronmarston** [comment]
Also, if we were to rescue errors thrown by your `==` method, it would hide the issue from you.

**Comment by JonRowe** [comment]
Exactly, the most I'd want to do here would be rescue the error and raise a more informative message prehaps

**Comment by mhenrixon** [comment]
A more informative message would be much appreciated.

**Comment by myronmarston** [comment]
> A more informative message would be much appreciated.

Want to take a stab at it?

**Comment by mhenrixon** [comment]
> Want to take a stab at it?

Oh boy.... This is hard without overdoing it but let me try.

**Comment by mhenrixon** [comment]
Maybe slap on something about comparing mock to real object or that the AnyArgs marcher will provide a much and not a real object? How to formulate that without sounding like a douche or an idiot. Let me ponder a few minutes on this one.

**Comment by myronmarston** [comment]
> Maybe slap on something about comparing mock to real object or that the AnyArgs marcher will provide a much and not a real object? How to formulate that without sounding like a douche or an idiot. Let me ponder a few minutes on this one.

The `any_args`/`anything` cases are particular special cases but the user my run into this for other cases as well, so the message shouldn't be limited to them.

**Comment by mhenrixon** [comment]
Point taken!

**Comment by JonRowe** [comment]
Something along the lines of:

> RSpec encountered an exception when checking arguments were called correctly, Ruby expects `#==` to return true or false for any object regardless of implementation so it is recommended that the implementation is fixed. The original error was: `NoMethodError: undefined method 'month' for #<RSpec::Mocks::ArgumentMatchers::AnyArgsMatcher:0x007f91b2c031b8>` maybe/

**Comment by mhenrixon** [comment]
Ah @JonRowe thats way better than what I had in mind.

**Comment by myronmarston** [comment]
I just opened 2 PRs that I think will avoid this issue:

* rspec/rspec-mocks#924
* rspec/rspec-support#193

Would those of you who have run into this issue want to try those PRs out?

**Comment by mhenrixon** [comment]
I'll do it, this weekend enough?

**Comment by myronmarston** [comment]
> I'll do it, this weekend enough?

Sure.

**Comment by mhenrixon** [comment]
Yup so that certainly fixes the issue I had at the time!! :+1:

**Comment by mhenrixon** [comment]
@myronmarston what is the expected rspec release version where these patches will be present? I am looking to upgrade for another reason now but this is hindering me.

**Comment by myronmarston** [comment]
3.3

**Comment by myronmarston** [comment]
For now you could upgrade to rspec HEAD by specifying each of the gems in your gemfile as pointing to github.

I'm hopeful 3.3 will be out in a few weeks, but no promises on that.
