### ISSUE TITLE
failure messages can't display non-ascii characters.

### ISSUE THREAD

**Issue by ratsbomb** [rspec/rspec-expectations#847]
I wrote feature specs using selenium-webdriver.
then I got failure message like following.
Question Marks are korean characters. 

## My Test Environment
```
 andrew  ~  workspace   ruby -v
ruby 1.9.3p547 (2014-05-14 revision 45962) [x86_64-linux]
 andrew  ~  workspace   bundle show | grep 'rspec'
  * rspec (3.3.0)
  * rspec-core (3.3.2)
  * rspec-expectations (3.3.1)
  * rspec-mocks (3.3.2)
  * rspec-rails (3.3.3)
  * rspec-support (3.3.0)

```

## Test Code
```
expect(page).to_not have_content(I18n.t("answers.text.mandatory_check"))
```

## Result
```
  1) Questionnaire has smartlogic in preview with 2 pages(no welcome), 1 page has smartlogic chosen Q1C1 in Page 1
     Failure/Error: expect(page).to_not have_content(I18n.t("answers.text.mandatory_check"))
       expected not to find text "???? ?????. ?? ??? ????." in "?? ??? ??? ????? ??? ??? ??? ??? ????. ???? ?????. ?? ??? ????. Q1 * ??? ??? ??? ??? ??? ??? ?? ???? ?????. ????? ????. ??? ??? ?? ??? ???? ??, ???. ??? ??? ??, ??.. ?????????????? ???? ??? ????? ??? ????? ????.. ??? ??? ??? ?? ??? ???? ?????????????? ???. ? ? ? ??? ???? ??? ??? ????. ??? ???? ?? ?? ??. "
```

**Comment by JonRowe** [comment]
This is an encoding issue between your source and your output, if your specs files are encoded properly (UTF-8?, you need to add a magic comment for 1.9.3) and selenium is encoding the browser contents properly (no guarentee) you should check the encoding of your terminal.

RSpec has a lot of protection against encoding errors so unless you can provide a specific, isolated, reproducible example I'm going to be on this being a local or selenium issue. Feel free to reopen if you can reproduce this outside of your app.

**Comment by DmitryBochkarev** [comment]
I can confirm for all versions after 3.0.4.

```
$ ls
Gemfile  Gemfile.lock  one_spec.rb
$ file one_spec.rb 
one_spec.rb: UTF-8 Unicode text
$ cat one_spec.rb 
# coding: utf-8

describe '1' do
  it { expect('ЙЦУКЕНГШЩ').to eq '' }
end
```
# rspec = 3.0.4

```
$ bundle env
Bundler 1.7.9
Ruby 1.9.3 (2014-11-13 patchlevel 551) [x86_64-linux]
Rubygems 2.4.8
rvm 1.26.11 (latest)
GEM_HOME /home/dmitry/.rvm/gems/ruby-1.9.3-p551
GEM_PATH /home/dmitry/.rvm/gems/ruby-1.9.3-p551:/home/dmitry/.rvm/gems/ruby-1.9.3-p551@global
rubygems-bundler (1.4.4)


Gemfile
source 'https://rubygems.org'

gem 'bundler'
gem 'rspec', '~> 3.0', '< 3.1'


Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    diff-lcs (1.2.5)
    rspec (3.0.0)
      rspec-core (~> 3.0.0)
      rspec-expectations (~> 3.0.0)
      rspec-mocks (~> 3.0.0)
    rspec-core (3.0.4)
      rspec-support (~> 3.0.0)
    rspec-expectations (3.0.4)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.0.0)
    rspec-mocks (3.0.4)
      rspec-support (~> 3.0.0)
    rspec-support (3.0.4)

PLATFORMS
  ruby

DEPENDENCIES
  bundler
  rspec (~> 3.0, < 3.1)
```

```
$ bundle exec rspec one_spec.rb 
F

Failures:

  1) 1 should eq ""
     Failure/Error: it { expect('ЙЦУКЕНГШЩ').to eq '' }
       
       expected: ""
            got: "ЙЦУКЕНГШЩ"
       
       (compared using ==)
     # ./one_spec.rb:4:in `block (2 levels) in <top (required)>'

Finished in 0.00057 seconds (files took 0.04058 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./one_spec.rb:4 # 1 should eq ""
```

# rspec = 3.1.0

```
$ bundle env
Bundler 1.7.9
Ruby 1.9.3 (2014-11-13 patchlevel 551) [x86_64-linux]
Rubygems 2.4.8
rvm 1.26.11 (latest)
GEM_HOME /home/dmitry/.rvm/gems/ruby-1.9.3-p551
GEM_PATH /home/dmitry/.rvm/gems/ruby-1.9.3-p551:/home/dmitry/.rvm/gems/ruby-1.9.3-p551@global
rubygems-bundler (1.4.4)


Gemfile
source 'https://rubygems.org'

gem 'bundler'
gem 'rspec', '3.1.0'
gem 'rspec-expectations', '3.1.0'


Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    diff-lcs (1.2.5)
    rspec (3.1.0)
      rspec-core (~> 3.1.0)
      rspec-expectations (~> 3.1.0)
      rspec-mocks (~> 3.1.0)
    rspec-core (3.1.7)
      rspec-support (~> 3.1.0)
    rspec-expectations (3.1.0)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.1.0)
    rspec-mocks (3.1.3)
      rspec-support (~> 3.1.0)
    rspec-support (3.1.2)

PLATFORMS
  ruby

DEPENDENCIES
  bundler
  rspec (= 3.1.0)
  rspec-expectations (= 3.1.0)
```

```
$ bundle exec rspec one_spec.rb 
F

Failures:

  1) 1 should eq ""
     Failure/Error: it { expect('?????????').to eq '' }
       
       expected: ""
            got: "?????????"
       
       (compared using ==)
     # ./one_spec.rb:4:in `block (2 levels) in <top (required)>'

Finished in 0.00059 seconds (files took 0.04176 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./one_spec.rb:4 # 1 should eq ""
```

**Comment by DmitryBochkarev** [comment]
i was looking in diff and found this https://github.com/rspec/rspec-expectations/compare/v3.0.4...v3.1.0#diff-fdbfe5adc6a673ea730e686b764c220dR103 i don't think that's a reason

**Comment by JonRowe** [comment]
Hmm, this seems to be an error on 1.9.3, it doesn't happen on 2.2.3

**Comment by DmitryBochkarev** [comment]
yep on 2.2.3 output is correct, but i cannot use ruby 2 :(

**Comment by JonRowe** [comment]
This is an issue in rspec-core that mangles the failure output.

**Comment by DmitryBochkarev** [comment]
thank you
