### ISSUE TITLE
Include location of spec file in raise_error warning

### ISSUE THREAD

**Issue by tgxworld** [rspec/rspec-expectations#917]
Related to https://github.com/rspec/rspec-expectations/pull/862

I upgraded RSpec today and noticed all the warnings. One thing I had difficulty with was to track down the spec files to fix. I think it will be easier to track down the spec file if the location or backtrace of the actual error can be printed in the warning.

## Before 
```
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Actual error raised was #<RateLimiter::LimitExceeded: RateLimiter::LimitExceeded>. Instead consider providing a specific error class or message. This message can be supressed by setting: `RSpec::Expectations.configuration.warn_about_potential_false_positives = false`. Called from /home/tgxworld/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/given_core-3.7.1/lib/given/rspec/monkey.rb:21:in `handle_matcher'.
```

## Proposed Warning
```
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Actual error raised was #<RateLimiter::LimitExceeded: RateLimiter::LimitExceeded> with backtrace: 
./lib/rate_limiter.rb:61:in `performed!'
  # ./lib/rate_limiter/on_create_record.rb:42:in `block in rate_limit'
  # ./lib/post_creator.rb:369:in `save_post'
  # ./lib/post_creator.rb:128:in `block in create'
  # ./lib/distributed_mutex.rb:21:in `synchronize'
  # ./lib/distributed_mutex.rb:5:in `synchronize'
  # ./lib/post_creator.rb:254:in `block in transaction'
  # ./lib/post_creator.rb:248:in `transaction'
  # ./lib/post_creator.rb:125:in `create'
  # ./spec/support/helpers.rb:42:in `create_post'
  # ./spec/models/topic_spec.rb:1494:in `block (3 levels) in <top (required)>'
  # ./spec/models/topic_spec.rb:1493:in `block (2 levels) in <top (required)>'
Instead consider providing a specific error class or message. This message can be supressed by setting: `RSpec::Expectations.configuration.warn_about_potential_false_positives = false`. Called from /home/tgxworld/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/given_core-3.7.1/lib/given/rspec/monkey.rb:21:in `handle_matcher'.
```

**Comment by JonRowe** [comment]
The location is in the warning, it's just being triggerd by an external gem you're using:
```
/home/tgxworld/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/given_core-3.7.1/lib/given/rspec/monkey.rb:21
```

Consider asking them to configure RSpec to ignore their source or do it yourself via `RSpec.configuration.filter_gems_from_backtrace :given_core`.

**Comment by tgxworld** [comment]
@JonRowe Thanks for clarifying :+1:
