### ISSUE TITLE
Improve error message for negative any_instance spy expectations

### ISSUE THREAD

**Issue by soulcutter** [rspec/rspec-expectations#920]
``` ruby
RSpec.describe "negative any_instance stubs" do
  it "says it's not supported" do
    foo = Class.new
    allow_any_instance_of(foo).to receive(:to_s)
    foo.new # some process that uses an instance
    expect_any_instance_of(foo).not_to have_received(:to_s)
  end
end
```

results in

```
Failures:

  1) negative any_instance stubs says it's not supported
     Failure/Error: expect_any_instance_of(foo).not_to have_received(:to_s)

     NoMethodError:
       undefined method `setup_any_instance_negative_expectation' for #<RSpec::Mocks::Matchers::HaveReceived:0x007fd5616b3be8>
       Did you mean?  setup_any_instance_expectation
     # ./example_spec.rb:100:in `block (2 levels) in <top (required)>'

Finished in 0.19928 seconds (files took 4.82 seconds to load)
1 example, 1 failure
```

If you run similar code with a positive expectation you get:

```
Failures:

  1) positive any_instance stubs says it's not supported
     Failure/Error: expect_any_instance_of(foo).to have_received(:to_s)
       Using expect_any_instance_of(...) with the `have_received` matcher is not supported.
     # ./example_spec.rb:110:in `block (2 levels) in <top (required)>'

Finished in 0.20091 seconds (files took 6.2 seconds to load)
1 example, 1 failure
```

The latter is a much better error message, and I think is appropriate for the negative expectation case as well.

**Comment by myronmarston** [comment]
Agreed.
